# Config file for automatic testing at travis-ci.org (all env variables set within Travis settings)
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
services:
  - postgresql
install:
  - cd onehundreddaysofcode
  - ls
  - pip install -r requirements/dev.txt
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - cd onehundreddaysofcode
  - ls
  - psql -c 'create database onehundreddaysofcode;' -U postgres
  - npm run lint
  - npm run build
  - flask lint
script:
  - flask test
after_success:
  - coveralls