sudo: false
language: python
python:
- 3.6
services:
- postgresql
- mongodb
install:
- cd onehundreddaysofcode
- pip install -r requirements/dev.txt
- nvm install 6.10
- nvm use 6.10
- npm install
before_script:
- black onehundreddaysofcode
- cd onehundreddaysofcode
- psql -c 'create database onehundreddaysofcode;' -U postgres
- npm run lint
- npm run build
script:
- flask test
- flask coverage
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: LCIXIC3mRJij3wFKekwrOXJ+KucoAbYcnISOZ8UGecyLoDXLGXc4kiXiNXn7ysUw6Jas7qe4O2+HyAoqouoaRUapZ71WNdGykhYQdsZsWSJnxaFVZKExwCJJdLhOz7S/dOljSteXpgRQwwDBrjmPG7DKPN+ucWjd+ZA/vqNrlO++7JS4QkUS3p7OUHks90ZmqiVbAOs8wsg1lJ0ZI3PAoHlORYIXoNUOXCmPWfD02mL+XKMH/NRwa/yfGSoiYKFJ2tr3ptEt5QJe2G8JSmb303772r6zFgjBBxP2gGcy+YjnXwN2Y/Vg151fygfrxzkuFUzEdTI81RXBWfdvozYJh9/TdFBJR2m01lbTSYW55nn8BbJ8UzglxhyvgizwDO4+7EA1qHyhgdxlVfr9HTzepxa54xzrxxVi5Y+js8J5Im8EyL2YV7teUYhu6DYH++LBum+S0PTSyJpPk3oWxHtuqfAuntYGfg5VmSQ8JLlmb8SWGouvSiFcsyBCkeA8hJVEkXrESnn3eA3yGrr0Ti0lrRYVmUKDftZKGywPq8wXesxilzoNrtQUp2FlDU2/NokKlf8KUXjF277MWaQmsX9e5Q3cgFtVBvWqeHX0hBuGkyaY1D1jRwNIf0NEbROpvEn6g3SUA3Zx2ztUlzg7cqagWC3POAFXmwmU8jMUizh6pYU=
  app: onehundreddaysofcode
  on:
    repo: stoltzmaniac/One-Hundred-Days-of-Code
