sudo: false
language: python
python:
- 3.6
services:
- postgresql
- mongodb
install:
- cd onehundreddaysofcode
- pip install -r requirements/dev.txt
- nvm install 6.10
- nvm use 6.10
- npm install
before_script:
- black onehundreddaysofcode
- cd onehundreddaysofcode
- psql -c 'create database onehundreddaysofcode;' -U postgres
- npm run lint
- npm run build
script:
- flask test
- flask coverage
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: YZOWwB6UcuF7xzK/A37bj7eV6xyZ0KlNO1LGAa9qg5B+5dUugFAyAzNoiQ6qITzJV9Q17Z3t+7DiLir0+/tEDFWR44O5z0naU6UR/X8BSY4kKJlowVtSkQUva9DxPdPpTm0iEoZtkTdKkNKuWYOvns55BxzPf+BOq6HC3X8rzUDMJYb6/AaOEDqM4TxGIkdvVhZ9wb40iRV3NJsNKuEnjwU3rtTDbEH7ttkuwn1nsV5FiYgMYlLTxt2WIMiIJCSLZe7oDe8vaw6izDeDEn623S2lOkOlHzReMIURrHvyCJnKGedGEgBno0YafxjMYnJllB5yJqChidKonXTZzC0KWwWbMjC6gAFu2mqxm2OH3hi9AzMARHl7OI6YYB/kFhvsZHYRU+NHEd/K7mhDHh7MHX1aHsgxxG1Yy8mTm41Kk0gLXLl9m7r8gwk4GRZdLAG8oT6zvceoyD9B+MJJT97gRhou3oZbqwBrWEQmOAVgBbhrEU8b5MbOb4O8Cbkh4VKATXpJN5F6u5w+r8Vjn4PI/HyyCDJvVr1fxnV6S/YulFRI323DaurbWCHXAC30Unj2xn/YAFISGqjRUXIdKam7Kk0zQTC8wezc1cPAgSdxxfZDOaHV4kdTcDUbTEgzGfCxgqKy682RFDOLEpnPTYTyU3xICnXCSVPDVEP+cowx2Ug=
  app: One-Hundred-Days-of-Code
  on:
    repo: stoltzmaniac/One-Hundred-Days-of-Code
