sudo: false
language: python
python:
- 3.6
services:
- postgresql
- mongodb
install:
- cd onehundreddaysofcode
- pip install -r requirements/dev.txt
- nvm install 6.10
- nvm use 6.10
- npm install
before_script:
- black onehundreddaysofcode
- cd onehundreddaysofcode
- psql -c 'create database onehundreddaysofcode;' -U postgres
- npm run lint
- npm run build
script:
- flask test
- flask coverage
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: pZ84Pe6VbVkyL//PUGxQUAXXhpRLFThu/7yPsLwPK7UFewzX4wRx3U61lsi75M/jbY5PaiJyzmLED69v9SO8zlo+LPdezqGb6Dwoxowk7kZv4jjvwDM0OV5z4H2X429H7U+fYXs1l5Q9kvr3yluRHUGqnUVsBQnVtPWa4QyZJwXGRijdrexLeZkSmd+2oca5iCAwBIQ5CqNT1m3xt2xzeCmufsIR4G1XqnMD+H8pamycO0t18nULD+ISZCrdtpbUdKVGr4Wgrk/gTp7rOTTVyZVLSlOOe+NDZeirVslY57LGT0iOLMi46KvGJS6DjWOknB5tBUpca3P4ZEDEQ5+QmydVbhGdyBCR+Bp8Hgd+EQzYVzzuzsEHRS+rYB317FrJDgHujvKGiwRQ2AwOXR+HGDM/9tTHstc9nNGDGYlaP3v1yNBmZHeT7LUQdLvqCNh9EVQsIcyI3Kp7j5rDINIuHcQUeZm9krxOnLmDz1LPY0oSuHtb3xOxSFaOqmZH6Gfb544wnvccSLIJa5jbeN0XSSkdqUuFtYqAPxYeOrJQ0hw5oRdfUc4SO157hBXbMOUMa++Eek658nSESmfwCTFso0u/kyg8PIJEBO0nuhOJfHGUc95BwUEW88Umy6hdlxg3qnGhBhq3NArWn1/hxGTRTDUYkJlWEGDZ55FRPKMKNa8=
  app: onehundreddaysofcode
  on:
    repo: stoltzmaniac/One-Hundred-Days-of-Code
