# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- FLASK_APP=onehundreddaysofcode/autoapp.py FLASK_DEBUG=1
python:
  - 3.6
services:
  - postgresql
install:
  - cd onehundreddaysofcode
  - pip install -r requirements/dev.txt
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - cd onehundreddaysofcode
  - psql -c 'create database onehundreddaysofcode;' -U postgres
  - npm run lint
  - npm run build
script:
  - flask test
after_success:
  - coveralls