sudo: false
language: python
python:
- 3.6
services:
- postgresql
- mongodb
install:
- cd onehundreddaysofcode
- pip install -r requirements/dev.txt
- nvm install 6.10
- nvm use 6.10
- npm install
before_script:
- black onehundreddaysofcode
- cd onehundreddaysofcode
- psql -c 'create database onehundreddaysofcode;' -U postgres
- npm run lint
- npm run build
script:
- flask test
- flask coverage
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: Y8t7DhOz8qxN/GHKNTrJqzCZNIpSxbMwWDnO5EM+MQNliZZzXOwysOiiulFZeUeoSr3b1GCuxd4iPVH1qmgqEBKbi+qgi8TW/0JdoDEJVPkyXlpkfM+vvGlWC1cTdm3V5cayR4nchPxoHnq7fhnpNaCvvaCHmHcEGOTQHNRoztsrHYtohIPsjIYuAd4g2ZCyiRlKiaqd8JV+KMZVD7MA5KD7qFvu5K9bbNt3mgcl7+M6MdukwfY0E+N+RraKOt7XrsY+hZdZ2Jm2VFvLbZaBq1rJ7O8Zq5vJnkM7OTSzBw0GklPzZjLONlJtE4ooM/j+Eki1L+xiDyLQtQ+yC0525pgz0jFnrnOrbb/hST7wvlQkxOZFsW74wY+8Kh0CdYO7vCuADiw9t2EZ2IK+1FeK5kj/d9Tcq8J7GjDDzSS4xsGufXjcZBOCYyz4Gl4ftM+v8UJcbUITJlRi5k67C1HtaS1BF2TtOGG/uJVdtvE9wqvs3/NVB1rdiZHDVInWtaKxXp2U0hnnwru6As/7FHrT96VyVNdgBcJDCZmIkfevdx5egHVXz7I9mlsiN7wpHTk5QMVdN1YYkoWLQhxJqZOrlHvHrbQzDrH4gtUYdWEK6NDQLw/c2eloT6nHJBYR30LVTazCOxu0jUEzZSOVmpasY08QJwHPKMaGsCcWzoMZeaQ=
  app: One-Hundred-Days-of-Code
  on:
    repo: stoltzmaniac/One-Hundred-Days-of-Code
